### ISSUE TITLE
Tealium 5.2.1 crash: NSDictionary was mutated while being enumerated

### ISSUE THREAD

**Issue by haitham-reda** [Tealium/tealium-ios#46]
Hello,

on crash logs i started to see crash from `Tealium iOS` lib, crash dump:

```
NSGenericException
MESSAGE	*** Collection <__NSDictionaryM: 0x1744539b0> was mutated while being enumerated.
```
 Also i'm using: `addPersistentDataSources` to append a `Dictionary` but that's upon initialisation of lib only.

**Comment by craigrouse** [comment]
Hello @haitham-reda. How soon after init are you using addPersistentDataSources? I suspect there may be a race condition somewhere, but it would be good to know exactly when you are calling this method to see if we can reproduce the issue. Are you seeing a lot of crashes for this issue, or does it only show sporadically? It would also be useful to know if the crash is isolated to particular devices or OS versions.

Thanks,

Craig.

**Comment by haitham-reda** [comment]
Hi @craigrouse , i use it right after initialiazation `newInstanceForKey:` , monitoring the crash rate it's fairly big ( bit less than 1,000 ), no pattern regarding iOS versions or devices.
We had this crash once or twice only before in prior releases, but now we're facing that number as this is the first usage of `addPersistentDataSources:` , before the current app version it wasn't really used.
Thanks.

**Comment by haitham-reda** [comment]
hi @craigrouse  , `addVolatileDataSources ` probably solves this issue as it states that write operation is appended to the end of background writing queue.

**Comment by haitham-reda** [comment]
hi @craigrouse  , any other suggestion apart from `volatile` ?

**Comment by jonathanswong** [comment]
Hi @haitham-reda .  We found a fix for this issue and it should be fixed in our next release.  Thanks.

**Comment by haitham-reda** [comment]
Thanks @jonwong-tealium , looking forward 🎉

**Comment by jonathanswong** [comment]
@haitham-reda Release 5.3.1 is available.  Please let us know if this problem still persists and file a new issue.  Thank you.

**Comment by haitham-reda** [comment]
thanks @jonwong-tealium 👍 will get back to you in case the problem persists.
